spring:
  data:
    mongodb:
      uri: mongodb://root:password111@localhost:27017/users?authSource=admin

      database: users
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  file:
    name: ../logs-parent/user-service.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7

app:
  message: "Hello"