spring:
  application:
    name: configserver
  profiles:
    active: native
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:\Users\Maiko\IdeaProjects\Microservices\daily-haul-microservices\configserver\src\main\resources\config

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"